config/routes.rb
Rails.application.routes.draw do

  get '/play', to: 'characters#play'
  post '/play', to: 'characters#character_play'
  get '/one_player', to: 'characters#one_player_mode_play'
  post '/one_player', to: 'characters#one_player_mode'
  post '/searchByLetter', to: 'characters#searchByLetter'
  root 'sessions#new'
  #I needed to make a way to post these forms to the controller - for instance below I made a post request to the winner method in the characters controller when a player wants to see the winner
  post '/winner', to: 'characters#winner'
  #The player will get redirected to a new page to see the winner - so I added that view to the pages in the resource below
  get '/searchByLetter', to: 'characters#index'
  get   '/signup', to: 'users#new'
  get   '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  resources :characters
  resources :points
  resources :users do
    resources :characters
  end

end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_point, only: [:show, :edit, :update, :destroy]

  # GET /points
  # GET /points.json
  def index
    @points = Point.all
  end

  # GET /points/1
  # GET /points/1.json
  def show
  end

  # GET /points/new
  def new
    @point = Point.new
  end

  # GET /points/1/edit
  def edit
  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(point_params)

    respond_to do |format|
      if @point.save
        format.html { redirect_to @point, notice: 'Point was successfully created.' }
        format.json { render :show, status: :created, location: @point }
      else
        format.html { render :new }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /points/1
  # PATCH/PUT /points/1.json
  def update
    respond_to do |format|
      if @point.update(point_params)
        format.html { redirect_to @point, notice: 'Point was successfully updated.' }
        format.json { render :show, status: :ok, location: @point }
      else
        format.html { render :edit }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point.destroy
    respond_to do |format|
      format.html { redirect_to points_url, notice: 'Point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point
      @point = Point.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def point_params
      params.fetch(:point, {})
    end
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/points/_form.html.erb
<%= form_with(model: point, local: true) do |form| %>
  <% if point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/points/edit.html.erb
<h1>Editing Point</h1>

<%= render 'form', point: @point %>

<%= link_to 'Show', @point %> |
<%= link_to 'Back', points_path %>

app/views/points/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Points</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @points.each do |point| %>
      <tr>
        <td><%= link_to 'Show', point %></td>
        <td><%= link_to 'Edit', edit_point_path(point) %></td>
        <td><%= link_to 'Destroy', point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Point', new_point_path %>

app/views/points/new.html.erb
<h1>New Point</h1>

<%= render 'form', point: @point %>

<%= link_to 'Back', points_path %>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_point_path(@point) %> |
<%= link_to 'Back', points_path %>